import { Professional } from "./professional";
import { Movie } from "./movie";

let p1 : Professional = new Professional ("Jacobo González", 39, "Hombre", 87, 190, "Pelirrojo", "Marrón", "Caucásico", false, "Español", 0, "Escritor");
let p2 : Professional = new Professional ("Esteban Espilbergo", 60, "Hombre", 96, 184, "Canoso", "Azul", "Caucásico", false, "Mexicano", 4, "Director");
let p3 : Professional = new Professional ("Jessica Vargas", 26, "Mujer", 60, 160, "Negro", "Marrón", "Mulata", false, "Colombiana", 0, "Actriz");
let p4 : Professional = new Professional ("Tomás Crucero", 50, "Hombre", 84, 175, "Marrón", "Marrón", "Caucásico", false, "Español", 2, "Actor");
let p5 : Professional = new Professional ("Jim Halpert", 58, "Hombre", 87, 190, "Rubio", "Azul", "Caucásico", false, "Estadounidense", 0, "Productor");

let actors : Professional[] = [p3, p4];

let movie : Movie = new Movie ("El señor de los ganchitos", 2002, "Española", "Aventura");
// console.log(movie.showProperties());
movie.setActors(actors);
movie.setDirector(p2);
movie.setDistributor("Farmer Bros.");
movie.setIsMCU(false);
movie.setLanguage("Español");
movie.setMainCharacterName("Fordo Gansón");
movie.setPlatform("HBO");
movie.setProducer(p5);
movie.setWriter(p1);
console.log("\n");
console.log(movie.getActors());
console.log("\n");
console.log(movie.getDirector());
console.log("\n");
console.log(movie.getDistributor());
console.log("\n");
console.log(movie.getGenre());
console.log("\n");
console.log(movie.getIsMCU());
console.log("\n");
console.log(movie.getLanguage());
console.log("\n");
console.log(movie.getMainCharacterName());
console.log("\n");
console.log(movie.getNationality());
console.log("\n");
console.log(movie.getPlatform());
console.log("\n");
console.log(movie.getProducer());
console.log("\n");
console.log(movie.getReleaseYear());
console.log("\n");
console.log(movie.getTitle());
console.log("\n");
console.log(movie.getWriter());
console.log("\n");
console.log(movie.showProperties());